# Definieert de taken die moeten worden uitgevoerd wanneer de workspace start
tasks:
  - name: Install Dependencies and Start Expo
    init: |
      # Verwijder bestaande node_modules en package-lock.json voor een schone start
      rm -rf node_modules package-lock.json
      # Installeer alle Node.js afhankelijkheden met --force om conflicten te negeren
      npm install --force
      # Wis de Expo cache
      npx expo start --clear
    command: |
      # Start de Expo development server met tunneling
      npm start --tunnel

# Definieert de poorten die moeten worden geopend
ports:
  - port: 8081 # Standaard Expo Metro Bundler poort
    onOpen: ignore # Negeer deze poort standaard, Expo zal de tunnel-URL geven
  - port: 19000 # Expo DevTools poort
    onOpen: ignore
  - port: 19001 # Expo bundler poort
    onOpen: ignore